### ISSUE TITLE
Method for getting all unbound variables appearing in expression

### ISSUE THREAD

**Issue by WieFel** [Sominemo/Math-Parser-Dart#1]
Hi @Sominemo, thank you so much for this cool package!

In my project I am parsing an expression using `MathNodeExpression.fromString`. But then I would need to know which variables appear within the expression, in order to fetch the values from the backend.

Would it be possible to add a method like `List<String> getVariables()` to the `MathNode` class, which returns a list of unbound variable names appearing in the expression?
e.g. `["a", "b"]` for an expression `a + b - 5`

**Comment by Sominemo** [comment]
Sure, I was actually considering that, I'll add this ASAP.

**Comment by WieFel** [comment]
@Sominemo thank you very much for the quick response.
Please report back when it's ready ;)

Edit: in my case it would be also important to be able to detect variables that contain dots (`.`), as my expressions might look like this: `(prgTechnology.fbHotWaterMeter.rActualFlow + prgTechnology.fbColdWaterMeter.rActualFlow) / 2`, where `prgTechnology.fbHotWaterMeter.rActualFlow` and `prgTechnology.fbColdWaterMeter.rActualFlow` would be the two variables appearing in the expression.

**Comment by WieFel** [comment]
Btw. I already have a function for it:
```
/// Returns a list of variables in the order they appear within the
/// given expression.
List<String> getVariableNames(String expression) {
  return RegExp(r"[a-zA-Z][\w\.]*")
      .allMatches(expression)
      .map((e) => e.group(0)!)
      .toList();
```

This at least works for my custom use case...

**Comment by Sominemo** [comment]
I just published version `1.3.1`

- New: `MathNodeExpression.getPotentialVariableNames()` analyzes given math expression string for possible use of variables. Refer to [documentation](https://pub.dev/documentation/math_parser/latest/math_parser/MathNodeExpression/getPotentialVariableNames.html) for rough edges before using it.
- New: `MathNodeExpression.builtInVariables` gives a list of built-in predefined variable names.
- New: `MathNodeExpression.isVariableNameValid()` lets you check if the parser can work with a given name.

```dart
final expr = '2*a+b';
final vars = MathNodeExpression.getPotentialVariableNames(
  expr,
  hideBuiltIns: true,
);

MathNodeExpression.fromString(
  expr,
  variableNames: vars,
  isImplicitMultiplication: false,
);
```

**Comment by WieFel** [comment]
@Sominemo wow! Awesome, thanks!

**Comment by WieFel** [comment]
@Sominemo I still have a small problem about my variables containing `.` characters.
For example the call of `getPotentialVariableNames()` on the expression
```
(prgTechnology.fbHotWaterMeter.rActualFlow + prgTechnology.fbColdWaterMeter.rActualFlow) / 2
```
yields
```
[prgTechnology, fbHotWaterMeter, rActualFlow, fbColdWaterMeter]
```
whereas I would expect it to be:
```
[prgTechnology.fbHotWaterMeter.rActualFlow, prgTechnology.fbColdWaterMeter.rActualFlow]
```

Is it possible to include custom chars (e.g. the dot) into allowed characters for variable names?
If not, i will just use my regex solution for now, as my use case is a little specific...

**Comment by Sominemo** [comment]
Period is not an allowed character for variable names even if you specify them manually, and I'm not sure if it's a good idea to make it one

**Comment by WieFel** [comment]
Ok, so do you think doing for example
```dart
MathNodeExpression.fromString(
  '(prgTechnology.fbHotWaterMeter.rActualFlow + prgTechnology.fbColdWaterMeter.rActualFlow) / 2',
).calc(
  MathVariableValues({'prgTechnology.fbHotWaterMeter.rActualFlow': 20, 'prgTechnology.fbColdWaterMeter.rActualFlow': 5}),
);
```
will also be a problem?

My idea would have been to maybe make it possible to override the variable name parsing function or to whitelist additional allowed chars using a prop.

**Comment by Sominemo** [comment]
> will also be a problem?

You forgot to declare used variables in `toString` call, that will be a problem 🙂
And if you'd declare the names, the variable checker would've raised an exception about illegal characters in your variable name.

In general, your suggestion makes sense, I'll see what can I do.

**Comment by WieFel** [comment]
> > will also be a problem?
> 
> You forgot to declare used variables in `toString` call, that will be a problem 🙂 And if you'd declare the names, the variable checker would've raised an exception about illegal characters in your variable name.
> 
> In general, your suggestion makes sense, I'll see what can I do.

Ok thanks! I think meanwhile I can circumvent this by just replacing all `.` with `_` within the expression right before doing all the calculation stuff, right?

**Comment by Sominemo** [comment]
> replacing all `.` with `_`

That will certainly work

**Comment by Sominemo** [comment]
I published version 1.4.0 which allows to use period in the middle of a variable name (but can't be first or last character). I'm afraid I couldn't allow use of custom characters.
